### ISSUE TITLE
unable to locate HDF5 header file at hdf5.h stack traceback:

### ISSUE THREAD

**Issue by flystarhe** [xinario/SAGAN#1]
torch/install/share/lua/5.1/hdf5/ffi.lua:42: Error: unable to locate HDF5 header file at hdf5.h
stack traceback:
	[C]: in function 'error'
	/home/hejian/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	test.lua:10: in main chunk
	[C]: in function 'dofile'
	...jian/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

请问,你有遇到吗?是怎样处理的,我在Ubuntu下尝试运行的?网上的方法试了不少,还是报错...

**Comment by xinario** [comment]
Is the hdf5.h file inside your include path?
The path can be found in   [your torch folder]/install/share/lua/5.1/hdf5/config.lua  specified as HDF5_INCLUDE_PATH

**Comment by flystarhe** [comment]
I try:
```
luarocks install hdf5
```
or:
```
sudo apt-get install libhdf5-serial-dev hdf5-tools
git clone https://github.com/deepmind/torch-hdf5
cd torch-hdf5
luarocks make hdf5-0-0.rockspec LIBHDF5_LIBDIR="/usr/lib/x86_64-linux-gnu/"
```

not find `hdf5@1.8/1.8.18/include` for `~/torch/install/share/lua/5.1/hdf5/config.lua`:
```
hdf5._config = {
    HDF5_INCLUDE_PATH = "",
    HDF5_LIBRARIES = "/home/hejian/anaconda3/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so"
}
```
installed hdf5 dir:
```
hejian@xlab:~$ tree -L 3 /home/hejian/torch/install/lib/luarocks/rocks/hdf5/
/home/hejian/torch/install/lib/luarocks/rocks/hdf5/
└── 0-0
    ├── doc
    │   ├── hdf5.md
    │   └── usage.md
    ├── hdf5-0-0.rockspec
    └── rock_manifest

2 directories, 4 files
```

**Comment by flystarhe** [comment]
thx, find it at `/usr/lib/x86_64-linux-gnu/hdf5/serial/`. I'll try it again.
@Ubuntu 16.04

**Comment by xinario** [comment]
Great, just specify the include path in config.lua. For example in my case it is:
HDF5_INCLUDE_PATH = "/usr/include/hdf5/serial"

**Comment by flystarhe** [comment]
Thank you very much for your contribution.

I ran your model, the effect is amazing. I also want to do some experiments in this area, but the paired CT scan data provided by the doctor are difficult to align. How did your paired training data get?

**Comment by xinario** [comment]
Most likely you'll have to register the images by yourself. Actually, we are trying to release our scanned piglet data for research purpose.  Please stay tuned:)
