### ISSUE TITLE
 DATA_ROOT: command not found

### ISSUE THREAD

**Issue by houguanqun** [xinario/SAGAN#2]
您好，我在复现您的工作的时候，按照您GitHub上的步骤来进行，install torch和其他packages，然后在clone项目时是直接下载下来放到服务器上（一个sagan-master的文件夹），接着我不能Download the pretrained denoising model ，因为链接在国内失效了，我猜测；接着Prepare test set成功，显示：318 files in the folder；but 当我 test the model时，显示： DATA_ROOT: command not found，我在想是不是预训练模型的问题，不知道您有没有解决办法，谢谢！

**Comment by xinario** [comment]
1. 我把训练好的模型在度盘上传了一份
链接: https://pan.baidu.com/s/1N4U8R0jU8_jm5iCPuGWNuw 密码: 5gv4

2. 确保你在run 命令[DATA_ROOT=./datasets/experiment name=SAGAN which_direction=AtoB phase=test th test.lua]的时候DATA_ROOT后面没有空格， 找不到模型报的错不是这样的。

**Comment by houguanqun** [comment]
之前的问题解决了，应该是空格的原因，谢谢师兄。
       另外，师兄，您提供给我的预训练好的模型是需要新建一个文件夹checkpoints，然后放在里面么，我这么做之后并没有生成train.h5文件，而是生成了input，output和target三个空文件夹。




发自网易邮箱大师
在2018年4月4日 11:37，Xin Yi<notifications@github.com> 写道：

我把训练好的模型在度盘上传了一份
链接: https://pan.baidu.com/s/1N4U8R0jU8_jm5iCPuGWNuw 密码: 5gv4

确保你在run 命令[DATA_ROOT=./datasets/experiment name=SAGAN which_direction=AtoB phase=test th test.lua]的时候DATA_ROOT后面没有空格， 找不到模型报的错不是这样的。

**Comment by houguanqun** [comment]
这个问题解决了，谢谢您！




发自网易邮箱大师
在2018年4月4日 15:31，hougqtsinghua<hougqtsinghua@163.com> 写道：
       之前的问题解决了，应该是空格的原因，谢谢师兄。
       另外，师兄，您提供给我的预训练好的模型是需要新建一个文件夹checkpoints，然后放在里面么，我这么做之后并没有生成train.h5文件，而是生成了input，output和target三个空文件夹。




发自网易邮箱大师
在2018年4月4日 11:37，Xin Yi<notifications@github.com> 写道：

我把训练好的模型在度盘上传了一份
链接: https://pan.baidu.com/s/1N4U8R0jU8_jm5iCPuGWNuw 密码: 5gv4

确保你在run 命令[DATA_ROOT=./datasets/experiment name=SAGAN which_direction=AtoB phase=test th test.lua]的时候DATA_ROOT后面没有空格， 找不到模型报的错不是这样的。
